# Generated by Django 2.0.3 on 2018-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', help_text='About yourself. 1000 characters or less.', max_length=1000, verbose_name='bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(default='<django.db.models.fields.EmailField>', max_length=100, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer.                                            Letters, digits and . / - / _ only.', max_length=150, verbose_name='username'),
        ),
    ]
