# Generated by Django 2.0.4 on 2018-05-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_auth', '0002_user_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='<django.db.models.fields.EmailField>', max_length=150, verbose_name='username'),
        ),
    ]
