# Generated by Django 2.0.3 on 2018-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_auth', '0002_auto_20180314_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(default='<django.db.models.fields.EmailField>', max_length=100, verbose_name='username'),
        ),
    ]
