# Generated by Django 2.0.5 on 2018-05-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crux_auth', '0003_auto_20180513_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp',
        ),
    ]
