# Generated by Django 2.0.5 on 2018-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_auth', '0004_remove_user_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
