# Generated by Django 2.0.3 on 2018-04-11 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crux_app', '0002_auto_20180407_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(related_name='dataset_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
