# Generated by Django 2.0.4 on 2018-04-11 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0003_auto_20180411_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'permissions': (('owner', 'Superuser access'), ('editor', 'Can view, edit, comment, share but not delete'), ('commenter', 'Can view, comment but not edit or delete'), ('viewer', 'Can only view dataset'))},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
