# Generated by Django 2.0.3 on 2018-03-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0003_auto_20180330_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crux_app.Dataset'),
        ),
    ]
