# Generated by Django 2.0.4 on 2018-04-11 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0004_auto_20180411_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
    ]
