# Generated by Django 2.0.4 on 2018-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0006_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(blank=True, help_text='500 characters or fewer.', max_length=500, verbose_name='description'),
        ),
    ]
