# Generated by Django 2.0.3 on 2018-04-05 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0006_auto_20180405_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4b69a611-d09c-47b6-8f6f-97cbe9225d35'), editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
