# Generated by Django 2.0.4 on 2018-04-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0007_auto_20180411_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('DS', 'Dataset'), ('TA', 'Task')], default='DS', max_length=2, verbose_name='file_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crux_app.Task'),
        ),
        migrations.AlterField(
            model_name='file',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crux_app.Dataset'),
        ),
    ]
