# Generated by Django 2.0.3 on 2018-04-05 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0007_auto_20180405_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
