# Generated by Django 2.0.4 on 2018-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0008_auto_20180411_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('DS', 'Dataset'), ('TA', 'Task')], max_length=2, verbose_name='file_type'),
        ),
    ]
