# Generated by Django 2.0.4 on 2018-04-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0009_auto_20180411_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='description'),
            preserve_default=False,
        ),
    ]
