# Generated by Django 2.0.4 on 2018-04-26 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crux_app', '0014_task_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 100 characters or fewer.', max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, help_text='500 characters or fewer.', max_length=500, verbose_name='description')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='crux_app.Dataset')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='crux_app.Task')),
            ],
            options={
                'permissions': (('owner', 'Superuser access'), ('editor', 'Can view, edit, comment, share but not delete'), ('commenter', 'Can view, comment but not edit or delete'), ('viewer', 'Can only view dataset')),
            },
        ),
    ]
