# Generated by Django 2.0.4 on 2018-04-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0016_auto_20180426_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='task',
        ),
        migrations.AddField(
            model_name='file',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crux_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('DS', 'Dataset'), ('AN', 'Analysis')], max_length=2, verbose_name='file_type'),
        ),
    ]
