# Generated by Django 2.0.4 on 2018-04-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0017_auto_20180426_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='Slug'),
        ),
    ]
