# Generated by Django 2.0.4 on 2018-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux_app', '0018_file_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
