query allAnalyses {
  allAnalyses {
    name
    slug
    dataset {
      slug
      name
      readme
    }
  }
}

query userAnalyses {
  userAnalyses {
    name
    slug
    dataset {
      slug
      name
      readme
    }
  }
}

query analysisBySlug($slug: String!) {
  analysisBySlug(slug: $slug) {
    name
    readme
    slug
    files {
      name
      slug
      content
    }
  }
}

mutation createAnalysis($name: String!, $readme: String, $datasetId: Int!) {
  createAnalysis(name: $name, readme: $readme, datasetId: $datasetId) {
    analysis {
      id
      name
      slug
    }
  }
}
