query allAnalyses {
  allAnalyses {
    name
    slug
    readme
    dataset {
      name
      slug
      readme
      files {
        name
        file
      }
    }
  }
}

query userAnalyses {
  userAnalyses {
    name
    slug
    readme
    dataset {
      name
      slug
      readme
      files {
        name
        file
      }
    }
  }
}

query analysisBySlug($slug: String!) {
  analysisBySlug(slug: $slug) {
    name
    readme
    slug
    files {
      name
      slug
      content
    }
  }
}

mutation createAnalysis($name: String!, $readme: String, $datasetId: Int!) {
  createAnalysis(name: $name, readme: $readme, datasetId: $datasetId) {
    analysis {
      id
      name
      slug
    }
  }
}
