# Generated by Django 2.0.5 on 2018-05-23 17:44

import app.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True,
                                                max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True,
                                               max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(
                    default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('bio', models.CharField(
                    help_text='About yourself. 1000 characters or less.', max_length=1000, verbose_name='bio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(editable=False)),
                ('kind', models.CharField(choices=[
                 ('CRE', 'CREATE'), ('UPD', 'UPDATE'), ('DEL', 'DELETE')], default='UPD', max_length=3)),
                ('object_id', models.PositiveIntegerField()),
                ('by', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('readme', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'default_related_name': 'analyses',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('readme', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('slug', models.SlugField(editable=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='files', to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'files',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('readme', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.Dataset')),
            ],
            options={
                'default_related_name': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='dataset',
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='app.Dataset'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='task',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='app.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('created_by', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('created_by', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together={('created_by', 'slug')},
        ),
    ]
