# Generated by Django 2.0.3 on 2018-03-28 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crux_datasets', '0004_auto_20180328_0101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 100 characters or fewer.', max_length=100, verbose_name='name')),
                ('file', models.FileField(upload_to='')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crux_datasets.Dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
